# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe450e70d7589ca0fabbac85c475aa5f299ccd2f400caa62af79acb6d5005bddcd72d20bc68da1ee96b380de9932382a3648e844ffb7aa5d32749be6053d43b

test:
  secret_key_base: 342ccf6f5866d873dc491a46f9e8f2de90ba858f1b9b3e6f3b9ca2850a6885e84332f9e1a95c12d82e4f1a275cb24b92d34600a24d7384b9e30583dc2dd260b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
